<template>
  <div class="row">
    <div class="col-12">
      <div class="card shadow">
        <div class="card-body">
          <div class="table-responsive">
            <table id="data-table" class="table table-hover w-100">
              <thead class="thead-light">
                <tr>
                  <th>姓名</th>
                  <th>電話</th>
                  <th>所在分部</th>
                  <th>年齡</th>
                  <th>到職日</th>
                  <th>薪資</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>蘇晉鵬</td>
                  <td>0949-586750</td>
                  <td>台北</td>
                  <td>61</td>
                  <td>2011/04/25</td>
                  <td>$320,800</td>
                </tr>
                <tr>
                  <td>邵擎宇</td>
                  <td>09-2068185</td>
                  <td>東京</td>
                  <td>63</td>
                  <td>2011/07/25</td>
                  <td>$170,750</td>
                </tr>
                <tr>
                  <td>任展鵬</td>
                  <td>0995-265037</td>
                  <td>舊金山</td>
                  <td>66</td>
                  <td>2009/01/12</td>
                  <td>$86,000</td>
                </tr>
                <tr>
                  <td>胡紹齊</td>
                  <td>0900-714243</td>
                  <td>彰化</td>
                  <td>22</td>
                  <td>2012/03/29</td>
                  <td>$433,060</td>
                </tr>
                <tr>
                  <td>朱鴻煊</td>
                  <td>0906-069763</td>
                  <td>崑山</td>
                  <td>33</td>
                  <td>2008/11/28</td>
                  <td>$162,700</td>
                </tr>
                <tr>
                  <td>陸燁霖</td>
                  <td>0919-545179</td>
                  <td>倫敦</td>
                  <td>61</td>
                  <td>2012/12/02</td>
                  <td>$372,000</td>
                </tr>
                <tr>
                  <td>汪金鑫</td>
                  <td>02-07036453</td>
                  <td>布拉格</td>
                  <td>59</td>
                  <td>2012/08/06</td>
                  <td>$137,500</td>
                </tr>
                <tr>
                  <td>萬文昊</td>
                  <td>06-0491396</td>
                  <td>西雅圖</td>
                  <td>55</td>
                  <td>2010/10/14</td>
                  <td>$327,900</td>
                </tr>
                <tr>
                  <td>胡昊焱</td>
                  <td>0987-323198</td>
                  <td>杜拜</td>
                  <td>39</td>
                  <td>2009/09/15</td>
                  <td>$205,500</td>
                </tr>
                <tr>
                  <td>薛正豪</td>
                  <td>02-69627935</td>
                  <td>屏東</td>
                  <td>23</td>
                  <td>2008/12/13</td>
                  <td>$103,600</td>
                </tr>
                <tr>
                  <td>呂天宇</td>
                  <td>0992-388176</td>
                  <td>布達佩斯</td>
                  <td>30</td>
                  <td>2008/12/19</td>
                  <td>$90,560</td>
                </tr>
                <tr>
                  <td>趙立果</td>
                  <td>0942-111363</td>
                  <td>莫斯科</td>
                  <td>22</td>
                  <td>2013/03/03</td>
                  <td>$342,000</td>
                </tr>
                <tr>
                  <td>孟志澤</td>
                  <td>0903-768176</td>
                  <td>紐奧良</td>
                  <td>36</td>
                  <td>2008/10/16</td>
                  <td>$470,600</td>
                </tr>
              </tbody>
              <tfoot class="thead-light">
                <tr>
                  <th>姓名</th>
                  <th>電話</th>
                  <th>所在分部</th>
                  <th>年齡</th>
                  <th>到職日</th>
                  <th>薪資</th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>